import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="grid grid-cols-2 grid-rows-1 min-h-ei">
        <div className="mt-20 p-6">
          <div className="text-primary text-4xl">
            <h1>Let us care about what people are going to eat.</h1>
          </div>
          <div className="mt-20 p-6">
            <ul className="grid grid-cols-2">
              <li className="text-2xl text-secondary">Special Meeting</li>
              <li className="text-2xl text-secondary">Wedding</li>
              <li className="text-2xl text-secondary">Party</li>
              <li className="text-2xl text-secondary">Hotels</li>
              <li className="text-2xl text-secondary">Family Events</li>
              <li className="text-2xl text-secondary">Concerts</li>
            </ul>
          </div>
        </div>

        <div className="relative">
          <Image
            src="/images/headphoto.jpeg"
            layout="fill"
            objectFit="cover"
            alt="soup"
          />
        </div>
      </section>
    </div>
  );
};

export default Home;
